name: Matrix Demo
on: [workflow_dispatch]
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14, 16]
        Operating-system: [ubuntu-latest, windows-latest]
        include: #  Additional Single Combination
          - node-version: 18
            Operating-system: ubuntu-latest
        exclude: 
          - node-version: 12
            Operating-system: windows-latest
    runs-on: ${{ matrix.Operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
      - name: Install Dependencies
        run:  |
          cd 04-Starting-Project/
          npm ci
      - name: Build Project
        run:  |
          cd 04-Starting-Project/
          npm run build



## Scenarios where you want to build on diffrent node versions