name: Reusable workflow
on:
 workflow_call:
  inputs:
    artifact-name:
      description: Then name of the deployable artifact
      required: false
      default: dist
      type: string
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & Uploading Application"