name: test-project
on: 
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest  

    ## Steps for the Node. Js Code to run
    steps:
      - name: Get Code from the repository
        uses: actions/checkout@v3
        with:
          repository: github-actions/01-Starting-Project
          path: 01-Starting-Project

      - name: Install NodeJS 
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Install Dependencies
        run: npm ci
                
      - name: : Run tests
        run: npm test



        
